
@if($commonsetting->theme_version == 'theme1')
@include('front.themes.theme1')
@elseif($commonsetting->theme_version == 'theme2')
@include('front.themes.theme2')
@elseif($commonsetting->theme_version == 'theme3')
@include('front.themes.theme3')
@elseif($commonsetting->theme_version == 'theme4')
@include('front.themes.theme4')
@elseif($commonsetting->theme_version == 'theme5')
@include('front.themes.theme5')
@elseif($commonsetting->theme_version == 'theme6')
@include('front.themes.theme6')
@elseif($commonsetting->theme_version == 'theme7')
@include('front.themes.theme7')
@elseif($commonsetting->theme_version == 'theme8')
@include('front.themes.theme8')
@elseif($commonsetting->theme_version == 'theme9')
@include('front.themes.theme9')
@endif